title: Blog
author: Matt Qin
email: yongliqin0321@outlook.com
description: Just a blog.
favicon: "./favicon.ico"
url: https://yongli-qin.github.io/

# Build settings
remote_theme: huangyz0918/moving
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-last-modified-at

# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
    date-format: '%d-%b-%y'

moving:
  about_you: Developer
  avatar_url: "https://i.imghippo.com/files/TuBU2532dzo.jpg"
  date_format: "%b %d"
  back_to: "Index"
  social_links:
    github:  YongLi-Qin

